theme[main_bg]="#202020"
theme[main_fg]="#f0f0f0"
theme[title]="#f0f0f0"
theme[hi_fg]="#008ec4"

theme[selected_bg]="#202020"
theme[selected_fg]="#008ec4"
theme[inactive_fg]="#d9d9d9"

theme[graph_text]="#a79c14"
theme[meter_bg]="#202020"
theme[proc_misc]="#a79c14"

theme[cpu_box]="#008ec4"
theme[mem_box]="#10a778"
theme[net_box]="#523b78"
theme[proc_box]="#c30670"

theme[div_line]="#d9d9d9"

theme[temp_start]="#a79c14"
theme[temp_mid]="#523b78"
theme[temp_end]="#c30670"

theme[cpu_start]="#008ec4"
theme[cpu_mid]="#20a4b9"
theme[cpu_end]="#10a778"

theme[free_start]="#10a778"
theme[free_mid]="#10a778"
theme[free_end]="#20a4b9"

theme[cached_start]="#523b78"
theme[cached_mid]="#523b78"
theme[cached_end]="#008ec4"

theme[available_start]="#a79c14"
theme[available_mid]="#c30670"
theme[available_end]="#c30670"

theme[used_start]="#523b78"
theme[used_mid]="#523b78"
theme[used_end]="#c30670"

theme[download_start]="#008ec4"
theme[download_mid]="#008ec4"
theme[download_end]="#523b78"

theme[upload_start]="#008ec4"
theme[upload_mid]="#008ec4"
theme[upload_end]="#523b78"

theme[process_start]="#008ec4"
theme[process_mid]="#20a4b9"
theme[process_end]="#10a778"
